### ISSUE TITLE
RAM issue in one hot encoding

### ISSUE THREAD

**Issue by VieVie31** [ViCCo-Group/SPoSE#1]
Hi !

First of all, thank you for sharing your code.
I'm trying to run it on my machine and struggle with a memory error : 

```
Traceback (most recent call last):
  File "main.py", line 420, in <module>
    plot_dims=args.plot_dims,
  File "main.py", line 154, in run
    I = torch.eye(n_items)
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 8546033689600 bytes. Buy new RAM!
```

I ran the exact same line that you given in your `README.md`: `python main.py --task odd_one_out --modality behavioral/ --triplets_dir ./triplets/behavioral/ --learning_rate 0.001 --lmbda 0.008 --embed_dim 90 --batch_size 100 --epochs 500 --window_size 20 --sampling_method soft --p 0.7 --plot_dims --device cuda:0 --rnd_seed 42`

https://github.com/ViCCo-Group/SPoSE/blob/b6ad8cde9f11dd68a12430d1f09f4d277edd85c8/main.py#L154

It seems you create a huge matrix for storring one-hot encoded triplet which can't fit in RAM (the same problem happen both with CPU and CUDA).

I'm wondering why this issue didn't raised with your machine, maybe do you have much more RAM ? for my part I've a 32go CPU RAM...
Do you have any idea how to resolve such a problem ?

Best Regards,
Olivier

**Comment by LukasMut** [comment]
Hi Olivier,

could you please let me know about the dataset you happen to use, specifically about the number of items the dataset contains?

I have never encountered such an error before. The dataset used in the original paper consists of 1854 items, which results in an 1854 x 1854 identity matrix. This is not huge at all. I've recently run the script on a dataset that contains significantly more items (approx. 22k), and have not faced any memory errors. It seems as if you use an enormous number of items.

Cheers

Lukas

**Comment by VieVie31** [comment]
Hi Lukas !

Thank you for your answer, I'm using the behavioral triplets dataset which I splitted in 2 files : train_90.txt and test_10.txt.
The train_90.txt contains 1315512 lines.

Best Regards,
Olivier

**Comment by LukasMut** [comment]
Hi Olivier,

The lines do not correspond to the number of items. Have you pulled the most recent version of our code? The number of items is 1854. I've implemented a line that automatically finds the number of unique items without the need to specify that manually (see code snippet below). Could you print the n_items?

` #number of unique items in the data matrix
    n_items = torch.max(train_triplets).item() + 1`

**Comment by VieVie31** [comment]
Hi Lukas,

It seems I misunderstood the repository purpose.
I got the triplet used in the _Nature_'20 experiment and wanted to reproduce the sparse embedding presented in _ICLR_'19 from those behavioral data.
I'll pull the most recent version and continue investigations.
Sorry for the inconvenience and thanks for your time !

Best Regards,
Olivier
